Not yet usable.

diff --git a/update-passwd.in b/update-passwd.in
--- a/update-passwd.in
+++ b/update-passwd.in
@@ -3,12 +3,22 @@
 # Merge Fink's passwd and group additions into NetInfo
 #
 
+#NOTE:
+# AKH, 3 December 2012: Not yet usable, but I wanted to get it into public
+
 if [ `id -u` -ne 0 ]; then
 	echo "You must be root to run update-passwd."
 	exit 1
 fi
 
 PREFIX=@PREFIX@
+
+name="$1"
+info="$2"
+home="$3"
+shell="$4"
+groupname="$5"
+groupmembership="$6" 
 
 merge_user_info() {
 	FILE="$1"
@@ -21,16 +31,30 @@ merge_user_info() {
 			OIFS=$IFS
 			IFS=:
 			cat $FILE | grep $FINK_PASSWD_USER | while read name passwd uid gid junk1 junk2 junk3 info home shell; do
-				dscl . create /users/$name
-				dscl . create /users/$name name $name
-				dscl . create /users/$name passwd '*'
-				dscl . create /users/$name hint ""
-				dscl . create /users/$name uid $uid
-				dscl . create /users/$name gid $gid
-				dscl . create /users/$name home "$home"
-				dscl . create /users/$name shell "$shell"
-				dscl . create /users/$name realname "$info"
-				dscl . delete /users/$name AuthenticationAuthority
+				idtest=`/usr/bin/id $uid 2>/dev/null`
+				if [ "x$idtest" = "x" ] ; then
+					dscl . create /users/$name
+					dscl . create /users/$name name $name
+					dscl . create /users/$name passwd '*'
+					dscl . create /users/$name hint ""
+					dscl . create /users/$name uid $uid
+					dscl . create /users/$name gid $gid
+					dscl . create /users/$name home "$home"
+					dscl . create /users/$name shell "$shell"
+					dscl . create /users/$name realname "$info"
+					dscl . delete /users/$name AuthenticationAuthority
+				else
+					echo
+					echo "WARNING:  UID $uid is in use by:"
+					echo
+					echo $idtest
+					echo
+					echo "I am not overwriting this."
+					echo "You will need to edit $PREFIX/etc/passwd-fink manually"
+					echo "and set the UID entry for $FINK_PASSWD_USER to an unused"
+					echo "value."
+					echo
+				fi
 			done
 			IFS=$OIFS
 			;;
@@ -48,71 +72,147 @@ merge_group_info() {
 			OIFS=$IFS
 			IFS=:
 			cat $FILE | grep $GROUP | while read name passwd gid GroupMembership; do
-				dscl . create /groups/$name
-				dscl . create /groups/$name name $name
-				dscl . create /groups/$name passwd '*'
-				dscl . create /groups/$name gid $gid
-				dscl . create /groups/$name GroupMembership $GroupMembership
+				gidtest=`dscl . list Groups PrimaryGroupID | grep $gid`
+				if [ "x$gidtest" = "x" ] ; then
+					dscl . create /groups/$groupname
+					dscl . create /groups/$groupname name $groupname
+					dscl . create /groups/$groupname passwd '*'
+					dscl . create /groups/$groupname gid $gid
+					dscl . create /groups/$groupname GroupMembership $GroupMembership
+				else
+					echo
+					echo "WARNING: GID $gid is in use by:"
+					echo
+					echo $gidtest
+					echo
+					echo "I am not overwriting this."
+					echo "You will need to edit $PREFIX/etc/group-fink manually"
+					echo "and set the GID entry for $FINK_PASSWD_USER to an unused"
+					echo "value."
+					echo
+				fi
 			done
 			IFS=$OIFS
 			;;
 	esac
 }
 
-if [ ! $2 ]; then
+get_unused_id()
+
+if [ ! $1 ]; then
 	echo "No user was specified to be added."
 	echo "update-passwd needs to know which user will be added to the system."
 	exit 1
 fi
 
-if [ ! -f "$PREFIX/etc/passwd-fink" ]; then
-	echo "The file $PREFIX/etc/passwd-fink is missing."
-	echo "update-passwd can not continue without this file."
+if [ ! $6 ]; then
+	echo "update-passwd needs exactly 6 arguments."
 	exit 1
 fi
 
-if [ ! -f "$PREFIX/etc/group-fink" ]; then
-	echo "The file $PREFIX/etc/group-fink is missing."
-	echo "update-passwd can not continue without this file."
-	exit 1
+### dynamic UID/GID allocation
+
+uid=0
+gid=0
+# Test passwd.conf
+if [ "x"`grep AutoUid: $PREFIX/etc/fink.conf` = "x" ] ; then
+	#Auto ID
+	uidmin=`grep AutoUidMin $PREFIX/etc/fink.conf | cut d: -f2`
+	uidmax=`grep AutoUidMax $PREFIX/etc/fink.conf | cut d: -f2`
+	#uid
+	for test_id in {$uidmin..$uidmax} ; do
+		check_id=`id $test_id 2&>/dev/null | grep uid`
+		if [ "x"$check_id = "x" ] ; then 
+			uid=$check_uid
+			break
+		fi
+	done
+	if [ $uid -eq 0 ] ; then
+		printf "I couldn't find an unused UID in the range %d - %d.\n" $uidmin $uidmax 
+		printf "You may need to expand this range by editing $PREFIX/etc/fink.conf.\n"
+                exit 1
+	fi
+	#gid
+	for test_id in {$uidmin..$uidmax} ; do
+		check_id=`id $test_id 2&>/dev/null | grep gid`
+		if [ "x"$check_id = "x" ] ; then 
+			gid=$check_uid
+			break
+		fi
+	done
+	if [ $gid -eq 0 ] ; then
+		printf "I couldn't find an unused GID in the range %d - %d.\n" $uidmin $uidmax 
+		printf "You may need to expand this range by editing $PREFIX/etc/fink.conf.\n"
+	fi
 fi
 
-echo
-echo "The following user entry will be added to your NetInfo database:"
-grep `echo $2 | /usr/bin/sed "s/^passwd-//"` $PREFIX/etc/passwd-fink
+### check for existing user
+idcheck=`/usr/bin/id $name 2>/dev/null`
+if [ "x$idcheck" = "x" ]; then
+	echo
+	echo "The following user entry will be added to your DirectoryServices database:"
+	echo "RecordName: "$name
+	echo "UniqueID: "$uid
+	echo "Primary Group ID: "$gid
+	echo "RealName: "$info
+	echo "NFSHomeDirectory: "$home
+	echo "UserShell: "$shell
+	ADDUSER=1
+else 
+	echo "$USER user exists, with parameters:"
+	echo
+	echo $idcheck
+	echo
+	echo "Fink will use these."
+	ADDUSER=0
+end 
+### check for existing group here
+
 
 echo
-echo "The following group entry will be added to your NetInfo database:"
-grep `echo $2 | /usr/bin/sed "s/^passwd-//"` $PREFIX/etc/group-fink
+echo "The following group entry will be added to your DirectoryServices database:"
+grep $USER $PREFIX/etc/group-fink
 
 echo
-if [ "x$1" = "xpostinst" ]; then
-	echo "Existing entries with these names or numbers will be overwritten or"
-	echo "otherwise affected by this. On the other hand, some Fink packages will"
-	echo "not work unless these entries are in the NetInfo database. You can make"
-	echo "adjustments to the files $PREFIX/etc/passwd-fink and"
-	echo "$PREFIX/etc/group-fink now (from another window), then say yes here. Or"
-	echo "you can say no here and add the users and groups manually (e.g. on your"
-	echo "central NetInfo server). If you don't know what all of this is about,"
-	echo "just say yes."
-else
-	echo "Existing entries with these names or numbers will be overwritten or"
-	echo "otherwise affected by this."
-fi
+	echo "Some Fink packages will not work unless these entries are in the"
+	echo "DirectoryServices database. Fink can use existing entries with"
+	echo "these names, however, if they exist on the system, and this package"
+	echo "will check for them."
+	echo "You can also make any desired adjustments to the files"
+	echo "$PREFIX/etc/passwd-fink and $PREFIX/etc/group-fink" 
+	echo "now (from another window), then say yes here."
+	echo "Or you can say no here and add the users and groups manually"
+	echo "(e.g. on your central Open Directory server)." 
+	echo "If you don't know what all of this is about, it is safe to say yes."
 /bin/echo "Do you want to continue? [Y/n] \c"
 read answer
 
 answer=`echo $answer | sed 's/^[yY].*$/y/'`
 
-
 if [ -z "$answer" -o "x$answer" = "xy" ]; then
 	echo
-	echo "Merging user info..."
-	merge_user_info "$PREFIX/etc/passwd-fink" `echo $2 | /usr/bin/sed "s/^passwd-//"`
-
-	echo "Merging group info..."
-	merge_group_info "$PREFIX/etc/group-fink" `echo $2 | /usr/bin/sed "s/^passwd-//"`
-	echo "Done."
+	if [ "x$idcheck" = "x" ]; then
+		echo "Merging user info..."	
+		dscl . create /users/$name
+		dscl . create /users/$name name $name
+		dscl . create /users/$name passwd '*'
+		dscl . create /users/$name hint ""
+		dscl . create /users/$name uid $uid
+		dscl . create /users/$name gid $gid
+		dscl . create /users/$name home "$home"
+		dscl . create /users/$name shell "$shell"
+		dscl . create /users/$name realname "$info"
+		dscl . delete /users/$name AuthenticationAuthority
+	else
+		echo "$USER user exists, with parameters:"
+		echo
+		echo $idcheck
+		echo
+		echo "Fink will use these."
+	fi
+		echo "Merging group info..."
+		merge_group_info "$PREFIX/etc/group-fink" $USER
+		echo "Done."
 else
 	echo "Okay, not adding the entries."
 fi
